trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  helmVersion: 'v3.5.4'

steps:
- script: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh --version $helmVersion
  displayName: 'Install dependencies'
- script: helm lint --strict src/stable/f5-bigip-ctlr
  displayName: 'Checking linting'
