{{- if .Values.rbac.create -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "f5-bigip-ctlr.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "f5-bigip-ctlr.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
{{- end -}}
