{{- if .Values.rbac.create -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "f5-bigip-ctlr.fullname" . }}
  labels:
    app: {{ template "f5-bigip-ctlr.name" . }}
    chart: {{ template "f5-bigip-ctlr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
{{- end -}}
