{{- if or (not .Values.args.bigip_url) (not .Values.args.bigip_partition) }}
{{/*
Generate errors for missing required values.
*/}}
# {{required "BIG-IP url not specified - add to Values or pass with `--set` " .Values.args.bigip_url }}
# {{required "BIG-IP partition not specified - add to Values or pass with `--set` " .Values.args.bigip_partition }}
{{- else -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "f5-bigip-ctlr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "f5-bigip-ctlr.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "f5-bigip-ctlr.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceaccount }}
      containers:
      - name: {{ template "f5-bigip-ctlr.name" . }}
        image: "{{ .Values.image.user }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        env:
          - name: BIGIP_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.bigip_login_secret }}
                key: username
          - name: BIGIP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.bigip_login_secret }}
                key: password
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /app/bin/k8s-bigip-ctlr
        args:
        - --bigip-username
        - $(BIGIP_USERNAME)
        - --bigip-password
        - $(BIGIP_PASSWORD)
        {{- range $key, $value := .Values.args }}
        - --{{ $key | replace "_" "-"}}
        - {{ $value | quote }}
        {{- end }}
{{- end }}
